AppApplicants/AppApplicantsPresentation/Controllers/ApplicantsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using AppAplicantsBAL.Models;
using AppApplicants.Models;

namespace AppApplicantsPresentation.Controllers
{
    public class ApplicantsController : Controller
    {
        private IApplicants _repositoryApplicants;
        private BusinessApplicants repositoryApplicants = new BusinessApplicants();

        private IFile_Adjunts _repositoryFile_Adjunts;
        private BusinessFile_Adjunts repositoryFile_Adjunts = new BusinessFile_Adjunts();

        private IJobs _repositoryJobs;
        private BusinessJob repositoryJobs = new BusinessJob();

        //
        // GET: /Applicants/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            string Id = Request.QueryString["Id"];
            ApplicantView applicant = new ApplicantView();

            if (!string.IsNullOrEmpty(Id)) {

                Id = "27";

                applicant.Consecutive = Convert.ToInt32(Id);
                return RedirectToAction("Index", "Administrator", applicant);
            }

            
            applicant = FillJobs(applicant);

            applicant.file_Adjunt = new Files_Adjunt();

            ViewBag.cjobs = applicant.sjobs;

            ApplicantView applicantTemp = new ApplicantView();
            applicantTemp.SessionId = HttpContext.Session.SessionID;

            TempData["ModelApplicant"] = applicant;
            Session["SessionId"] = HttpContext.Session.SessionID;

            //Consult list files adjunt to the apllicants
            _repositoryFile_Adjunts = repositoryFile_Adjunts;
            TempData["ReportFiles_Adjunt"] = _repositoryFile_Adjunts.Consult_File_Adjunt(applicant.Consecutive.ToString());

            _repositoryApplicants = repositoryApplicants;
            TempData["ReportApplicants"] = _repositoryApplicants.Consult_Applicants(applicant.Consecutive.ToString());

            return View(applicant);
        }

        //
        // POST: /Applicants/Create

        [HttpPost]
        public ActionResult Create(ApplicantView applicantView)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    applicantView.PathPhotoLocal = "";
                    applicantView.PathPhotoURL = "";

                    _repositoryApplicants = repositoryApplicants;

                    int Id_Applicant = _repositoryApplicants.Create_Applicants(Convert.ToInt32(applicantView.ID_Job.ToString()),
                    applicantView.Firts_Name,
                    applicantView.Second_Name,
                    applicantView.First_Last_Name,
                    applicantView.Second_Last_Name,
                    applicantView.Email,
                    applicantView.International_Phone_Number,
                    applicantView.Biography,
                    applicantView.Birtday,
                    applicantView.Street_Adress,
                    applicantView.City,
                    applicantView.Country,
                    applicantView.Postal_Code,
                    applicantView.PathPhotoLocal,
                    applicantView.PathPhotoURL
                    );

                    bool result = false;
                    if (Id_Applicant > 0)
                    {
                        _repositoryFile_Adjunts = repositoryFile_Adjunts;

                        string pathString = string.Format("{0}File_Adjunt\\{1}", Server.MapPath("~"), HttpContext.Session.SessionID.ToString());
                        string[] filePaths = Directory.GetFiles(pathString);
                        List<ListItem> files = new List<ListItem>();
                        foreach (string filePath in filePaths)
                        {
                            string.Format("{0}File_Adjunt\\{1}\\{2}", Server.MapPath("~"), HttpContext.Session.SessionID.ToString(), Path.GetFileName(filePath));

                            FileInfo file = new FileInfo(string.Format("{0}File_Adjunt\\{1}\\{2}", Server.MapPath("~"), HttpContext.Session.SessionID.ToString(), Path.GetFileName(filePath)));
                            decimal sizeFileNEW = Convert.ToDecimal(file.Length);

                            result = _repositoryFile_Adjunts.Create_File_Adjunt(Id_Applicant,
                            Path.GetFileName(filePath),
                            Path.GetExtension(filePath),
                            0,
                            Path.GetFullPath(filePath),
                            "",
                            Session["Description_File"].ToString());
                        }

                        pathString = string.Format("{0}Photo_Applicant\\{1}", Server.MapPath("~"), HttpContext.Session.SessionID.ToString());
                        filePaths = Directory.GetFiles(pathString);
                        files = new List<ListItem>();
                        foreach (string filePath in filePaths)
                        {
                            FileInfo file = new FileInfo(string.Format("{0}Photo_Applicant\\{1}\\{2}", Server.MapPath("~"), HttpContext.Session.SessionID.ToString(), Path.GetFileName(filePath)));
                            decimal sizeFileNEW = Convert.ToDecimal(file.Length);

                            result = _repositoryFile_Adjunts.Create_File_Adjunt(Id_Applicant,
                            Path.GetFileName(filePath),
                            Path.GetExtension(filePath),
                            0,
                            Path.GetFullPath(filePath),
                            "",
                            "");
                        }

                        //Send email to user

                        //It´s reload the view applicant
                        ApplicantView applicant = new ApplicantView();
                        applicant = FillJobs(applicant);
                        applicant.file_Adjunt = new Files_Adjunt();

                        string job_name = "";
                        foreach (var item in applicant.sjobs)
                        {
                            if (Convert.ToInt32(item.Value) == applicantView.ID_Job)
                            {
                                job_name = item.Text;
                            }
                        }

                        string FullName = applicantView.Firts_Name + " " + applicantView.Second_Name;
                        string FullLastName = applicantView.First_Last_Name + " " + applicantView.Second_Last_Name;

                        SendEmail(Id_Applicant, FullName, FullLastName, job_name, "Hemos recibido tu aplicación!", 1, applicantView.Email);

                        //Send email to administrator

                        SendEmail(Id_Applicant, FullName, FullLastName, job_name, "Nueva aplicación recibida", 2, applicantView.Email);


                        //It´s reload the view applicant
                        applicant = new ApplicantView();
                        applicant = FillJobs(applicant);
                        applicant.file_Adjunt = new Files_Adjunt();

                        ViewBag.cjobs = applicant.sjobs;

                        TempData["ModelApplicant"] = applicant;

                        //Consult list files adjunt to the apllicants
                        _repositoryFile_Adjunts = repositoryFile_Adjunts;
                        TempData["ReportFiles_Adjunt"] = _repositoryFile_Adjunts.Consult_File_Adjunt(applicant.Consecutive.ToString());

                        _repositoryApplicants = repositoryApplicants;
                        TempData["ReportApplicants"] = _repositoryApplicants.Consult_Applicants(applicant.Consecutive.ToString());
                    }

                }
            }
            catch (Exception ex)
            {

            }

            return View(applicantView);
        }

        //
        // GET: /Clientes/Edit/5

        public ActionResult Edit(int Consec_Applicant = 0)
        {
            ApplicantView applicantView = new ApplicantView();

            _repositoryApplicants = repositoryApplicants;

            IEnumerable<Report_Applicants> lstApplicant = _repositoryApplicants.Consult_Applicants(Consec_Applicant.ToString());

            return View(applicantView);
        }

        //
        // POST: /Applicants/Edit

        [HttpPost]
        public ActionResult Edit(ApplicantView applicantView)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _repositoryApplicants = repositoryApplicants;

                    Boolean resultado = _repositoryApplicants.Edit_Applicants(applicantView.Consecutive,
                    Convert.ToInt32(applicantView.ID_Job.ToString()),
                    applicantView.Firts_Name,
                    applicantView.Second_Name,
                    applicantView.First_Last_Name,
                    applicantView.Second_Last_Name,
                    applicantView.Email,
                    applicantView.International_Phone_Number,
                    applicantView.Biography,
                    applicantView.Birtday,
                    applicantView.Street_Adress,
                    applicantView.City,
                    applicantView.Country,
                    applicantView.Postal_Code,
                    applicantView.PathPhotoLocal,
                    applicantView.PathPhotoURL
                    );
                }
            }
            catch (Exception ex)
            {

            }

            return View(applicantView);

AppApplicants/AppApplicantsPresentation/Controllers/Report_ApplicantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppApplicantsPresentation.Controllers
{
    public class Report_ApplicantsController : Controller
    {
        //
        // GET: /Report_Applicants/

        public ActionResult Index()
        {
            return View();
        }

    }
}

AppApplicants/AppApplicantsPresentation/Views/Report_Applicants/Index.cshtml
@using AppAplicantsBAL.Models;
@model AppAplicantsBAL.Models.ApplicantView

<html>
<head>
    <title>Index</title>

    <link href="/Content/Site.css" rel="stylesheet" />
    
    <!-- Libs -->
    <script src="/Scripts/jquery-1.7.1.js"></script>
    
    <script type="text/jscript">

    </script>
</head>
<body>
    @{
        /*ApplicantView applicant = new ApplicantView();
        applicant = TempData["ModelReportApplicants"] as ApplicantView;*/

        AppApplicants.Models.Report_Applicants reportApplicants = new AppApplicants.Models.Report_Applicants();
        IEnumerable<AppApplicants.Models.Report_Applicants> lstReportApplicants = TempData["ReportApplicants"] as IEnumerable<AppApplicants.Models.Report_Applicants>;

        var grid = new WebGrid(lstReportApplicants, canPage: true, rowsPerPage: 5, selectionFieldName: "selectedRow", ajaxUpdateContainerId: "gridContent");
        grid.Pager(WebGridPagerModes.NextPrevious);
    }

    <div>
        @if (lstReportApplicants != null)
        {
            <div id="gridContent">
            @{
            var gridColumns = new List<WebGridColumn>();
            gridColumns.Add(grid.Column("Consecutive", "Consecutive"));
            gridColumns.Add(grid.Column("Job Id", "ID_Job"));
            gridColumns.Add(grid.Column("Job Name ", "Job_Name"));
            gridColumns.Add(grid.Column("First Name", "Firts_Name"));
            gridColumns.Add(grid.Column("Second Name", "Second_Name"));
            gridColumns.Add(grid.Column("First Last Name", "Firts_Last_Name"));
            gridColumns.Add(grid.Column("Second Last Name", "Second_Last_Name"));
            gridColumns.Add(grid.Column("Email", "Email"));
            gridColumns.Add(grid.Column("International Phone Number", "International_Phone_Number"));
            gridColumns.Add(grid.Column("Biography", "Biography"));
            gridColumns.Add(grid.Column("Birthdate", "Birtday"));
            gridColumns.Add(grid.Column("Street Adress", "Street_Adress"));
            gridColumns.Add(grid.Column("City", "City"));
            gridColumns.Add(grid.Column("Country", "Country"));
            gridColumns.Add(grid.Column("Postal Code", "Postal_Code"));

            gridColumns.Add(grid.Column("Edit", "Edit", canSort: false, style: "Edit_Applicant", format: (item) => Html.ActionLink("Edit", "Edit_Applicant", "Applicants", new { Consecutive = @item.Consecutive, Id_Job = @item.ID_Job, Job_Name = @item.Job_Name, Firts_Name = @item.Firts_Name, Second_Name = @item.Second_Name, Firts_Last_Name = @item.Firts_Last_Name, Second_Last_Name = @item.Second_Last_Name, Email = @item.Email, International_Phone_Number = @item.International_Phone_Number, Biography = @item.Biography, Birthdate = @item.Birtday, Street_Adress = @item.Street_Adress, City = @item.City, Country = @item.Country, Postal_Code = @item.Postal_Code, Modulo = 2 }, null)));
            }

            @grid.GetHtml(tableStyle: "webGrid",
            headerStyle: "header",
            alternatingRowStyle: "alt",
            selectedRowStyle: "select",
            columns: grid.Columns(gridColumns.ToArray())
            )

            @if (grid.HasSelection)
            {
                reportApplicants = (AppApplicants.Models.Report_Applicants)grid.Rows[grid.SelectedIndex].Value;
                        <b>Job Id</b> @reportApplicants.ID_Job<br />
                        <b>Job Name</b> @reportApplicants.Job_Name<br />
                        <b>First Name</b> @reportApplicants.Firts_Name<br />
                        <b>Second Name</b> @reportApplicants.Second_Name<br />
                        <b>First Last Name</b> @reportApplicants.First_Last_Name<br />
                        <b>Second Last Name</b> @reportApplicants.Second_Last_Name<br />
                        <b>First Name</b> @reportApplicants.Firts_Name<br />
                        <b>Second Name</b> @reportApplicants.Second_Name<br />
                        <b>Email</b> @reportApplicants.Email<br />
                        <b>International Phone Number</b> @reportApplicants.International_Phone_Number<br />
                        <b>Biography</b> @reportApplicants.Biography<br />
                        <b>Birthdate</b> @reportApplicants.Birtday<br />
                        <b>Street Address</b> @reportApplicants.Street_Adress<br />
                        <b>City</b> @reportApplicants.City<br />
                        <b>Country</b> @reportApplicants.Country<br />
                        <b>Postal Code</b> @reportApplicants.Postal_Code<br />
            }        
            </div>    
        }

    </div>
</body>
</html>